stages:
  - compile
  - create

cache:
  paths:
    - flare-engine
    - venv4dmgbuild
    - dmgbuild

compile_macos_engine:
  stage: compile
  tags:
    - macos
  before_script:
    - echo "remember to 'brew install cmake libvorbis sdl2 sdl2_image sdl2_mixer sdl2_ttf'"
  script:
    - rm -rf flare-engine || true # remove previous cache
    - git clone https://github.com/flareteam/flare-engine.git --depth 1
    - echo git clone https://github.com/flareteam/flare-game.git --depth 1
    - cd flare-engine
    - cmake .
    - make
    - ./package_osx.sh flare homebrew
    - mv flare_osx.tar.gz flare_osx_engine.tar.gz
    - shasum -a 256 flare_osx_engine.tar.gz > flare_osx_engine.tar.gz.sha256.txt
    - cat flare_osx_engine.tar.gz.sha256.txt
  artifacts:
    paths:
      - flare-engine/flare_osx_engine.tar.gz
      - flare-engine/flare_osx_engine.tar.gz.sha256.txt

create_macos_engine_dmg:
  stage: create
  tags:
    - macos
  before_script:
    - echo ""
  script:
    - rm -rf venv4dmgbuild || true # remove previous cache
    - rm -rf dmgbuild || true # remove previous cache
    - python3 -m venv venv4dmgbuild # will be cached for game
    - source venv4dmgbuild/bin/activate
    - git clone https://github.com/ludoza/dmgbuild.git # TODO install from pip, if package updated
    - cd dmgbuild
    - pip install -e .
    - cd ..
    - ./dmgbuild-flare.sh flare-engine/flare_osx_engine.tar.gz flare_engine.dmg
    - shasum -a 256 flare_engine.dmg > flare_engine.dmg.sha256.txt
    - cat flare_engine.dmg.sha256.txt
  artifacts:
    paths:
      - flare_engine.dmg
      - flare_engine.dmg.sha256.txt

compile_macos_game:
  stage: compile
  tags:
    - macos
  before_script:
    - echo "remember to 'brew install cmake libvorbis sdl2 sdl2_image sdl2_mixer sdl2_ttf'"
  script:
    - git clone https://github.com/flareteam/flare-game.git --depth 1
    - cd flare-engine
    - echo cmake .
    - echo make
    - ./package_osx.sh flare homebrew ../flare-game
    - mv flare_osx.tar.gz flare_osx_game.tar.gz
    - shasum -a 256 flare_osx_game.tar.gz > flare_osx_game.tar.gz.sha256.txt
    - cat flare_osx_game.tar.gz.sha256.txt
  artifacts:
    paths:
      - flare-engine/flare_osx_game.tar.gz
      - flare-engine/flare_osx_game.tar.gz.sha256.txt

create_macos_game_dmg:
  stage: create
  tags:
    - macos
  before_script:
    - echo ""
  script:
    - source venv4dmgbuild/bin/activate
    - ./dmgbuild-flare.sh flare-engine/flare_osx_game.tar.gz flare_game.dmg
    - shasum -a 256 flare_game.dmg > flare_game.dmg.sha256.txt
    - cat flare_game.dmg.sha256.txt
  artifacts:
    paths:
      - flare_game.dmg
      - flare_game.dmg.sha256.txt
